# name: CI/CD Pipeline with Auto-Promotion
 
# on:
#   push:
#     branches:
#       - dev
 
# jobs:
#   build-test:
#     name: Build and Test React App
#     runs-on: ubuntu-latest
 
#     steps:
#       # Step 1: Checkout Code
#       - name: Checkout Code
#         uses: actions/checkout@v3
 
#       # Step 2: Setup Node.js Environment
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
 
#       # Step 3: Install Dependencies
#       - name: Install Dependencies
#         run: npm install
 
#       # Step 4: Run Tests
#       - name: Run Tests
#         run: npm test -- --watchAll=false
 
#       # Step 5: Build the App
#       - name: Build App
#         run: npm run build
 
#   auto-merge-to-prod:
#     name: Auto-Merge to Prod
#     runs-on: ubuntu-latest
#     needs: build-test
#     if: success()
 
#     steps:
#       # Step 1: Checkout Code
#       - name: Checkout Code
#         uses: actions/checkout@v3
 
#       # Step 2: Configure Git User
#       - name: Configure Git User
#         run: |
#           git config --global user.name "Praneethgadagoni"
#           git config --global user.email "pgadagoni@anergroup.com"
 
#       # Step 3: Merge Dev into Prod with Automatic Conflict Resolution
#       - name: Merge Dev into Prod
#         run: |
#           git fetch origin
#           git checkout prod
#           git merge dev --strategy-option theirs --allow-unrelated-histories --no-edit
#           git push origin prod
 
#   deploy:
#     name: Deploy React App to AWS
#     runs-on: ubuntu-latest
#     needs: auto-merge-to-prod
 
#     steps:
#       # Step 1: Checkout Code
#       - name: Checkout Code
#         uses: actions/checkout@v3
 
#       # Step 2: Configure AWS Credentials
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1
 
#       # Step 3: Install Dependencies
#       - name: Install Dependencies
#         run: npm install
 
#       # Step 4: Run Build Command (if build folder does not exist)
#       - name: Run Build Command (if build folder does not exist)
#         run: |
#           if [ ! -d "build" ]; then
#             npm run build
#           fi
 
#       # Step 5: Sync to S3
#       - name: Sync to S3
#         run: aws s3 sync ./build s3://praneeth25 --delete


name: CI/CD for React App
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
 
    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
 
    # Install dependencies
    - name: Install dependencies
      run: npm install
 
    # Run tests
    - name: Run tests
      run: npm test -- --watchAll=false
 
    # Build the app
    - name: Build the app
      run: npm run build
 
    # Deploy to Netlify
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3
      with:
        publish-dir: ./build
        production-deploy: true
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}